import 'model/video.dart';

List<Video> videoListForTest = [
  Video(
    id: '1',
    userId: 'user1',
    title: 'Video 1',
    description: 'Description 1',
    category: 'Category 1',
    labels: ['label1', 'label2'],
    coverUrl: 'http://example.com/cover1.jpg',
    videoUrl: 'http://example.com/video1.mp4',
    viewCount: 100,
    likeCount: 10,
    commentCount: 5,
    createdAt: 1633036800,
    updatedAt: 1633123200,
    deletedAt: 0,
    status: 'active',
  ),
  Video(
    id: '1',
    userId: 'user1',
    title: 'Video 1',
    description: 'Description 1',
    category: 'Category 1',
    labels: ['label1', 'label2'],
    coverUrl: 'http://example.com/cover1.jpg',
    videoUrl: 'http://example.com/video1.mp4',
    viewCount: 100,
    likeCount: 10,
    commentCount: 5,
    createdAt: 1633036800,
    updatedAt: 1633123200,
    deletedAt: 0,
    status: 'active',
  ),
  Video(
    id: '1',
    userId: 'user1',
    title: 'Video 1',
    description: 'Description 1',
    category: 'Category 1',
    labels: ['label1', 'label2'],
    coverUrl: 'http://example.com/cover1.jpg',
    videoUrl: 'http://example.com/video1.mp4',
    viewCount: 100,
    likeCount: 10,
    commentCount: 5,
    createdAt: 1633036800,
    updatedAt: 1633123200,
    deletedAt: 0,
    status: 'active',
  ),
  Video(
    id: '1',
    userId: 'user1',
    title: 'Video 1',
    description: 'Description 1',
    category: 'Category 1',
    labels: ['label1', 'label2'],
    coverUrl: 'http://example.com/cover1.jpg',
    videoUrl: 'http://example.com/video1.mp4',
    viewCount: 100,
    likeCount: 10,
    commentCount: 5,
    createdAt: 1633036800,
    updatedAt: 1633123200,
    deletedAt: 0,
    status: 'active',
  ),
  Video(
    id: '1',
    userId: 'user1',
    title: 'Video 1',
    description: 'Description 1',
    category: 'Category 1',
    labels: ['label1', 'label2'],
    coverUrl: 'http://example.com/cover1.jpg',
    videoUrl: 'http://example.com/video1.mp4',
    viewCount: 100,
    likeCount: 10,
    commentCount: 5,
    createdAt: 1633036800,
    updatedAt: 1633123200,
    deletedAt: 0,
    status: 'active',
  ),
  Video(
    id: '1',
    userId: 'user1',
    title: 'Video 1',
    description: 'Description 1',
    category: 'Category 1',
    labels: ['label1', 'label2'],
    coverUrl: 'http://example.com/cover1.jpg',
    videoUrl: 'http://example.com/video1.mp4',
    viewCount: 100,
    likeCount: 10,
    commentCount: 5,
    createdAt: 1633036800,
    updatedAt: 1633123200,
    deletedAt: 0,
    status: 'active',
  ),
  Video(
    id: '1',
    userId: 'user1',
    title: 'Video 1',
    description: 'Description 1',
    category: 'Category 1',
    labels: ['label1', 'label2'],
    coverUrl: 'http://example.com/cover1.jpg',
    videoUrl: 'http://example.com/video1.mp4',
    viewCount: 100,
    likeCount: 10,
    commentCount: 5,
    createdAt: 1633036800,
    updatedAt: 1633123200,
    deletedAt: 0,
    status: 'active',
  ),
  Video(
    id: '1',
    userId: 'user1',
    title: 'Video 1',
    description: 'Description 1',
    category: 'Category 1',
    labels: ['label1', 'label2'],
    coverUrl: 'http://example.com/cover1.jpg',
    videoUrl: 'http://example.com/video1.mp4',
    viewCount: 100,
    likeCount: 10,
    commentCount: 5,
    createdAt: 1633036800,
    updatedAt: 1633123200,
    deletedAt: 0,
    status: 'active',
  ),
  Video(
    id: '1',
    userId: 'user1',
    title: 'Video 1',
    description: 'Description 1',
    category: 'Category 1',
    labels: ['label1', 'label2'],
    coverUrl: 'http://example.com/cover1.jpg',
    videoUrl: 'http://example.com/video1.mp4',
    viewCount: 100,
    likeCount: 10,
    commentCount: 5,
    createdAt: 1633036800,
    updatedAt: 1633123200,
    deletedAt: 0,
    status: 'active',
  ),
  Video(
    id: '1',
    userId: 'user1',
    title: 'Video 1',
    description: 'Description 1',
    category: 'Category 1',
    labels: ['label1', 'label2'],
    coverUrl: 'http://example.com/cover1.jpg',
    videoUrl: 'http://example.com/video1.mp4',
    viewCount: 100,
    likeCount: 10,
    commentCount: 5,
    createdAt: 1633036800,
    updatedAt: 1633123200,
    deletedAt: 0,
    status: 'active',
  ),
];
